/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personal_finance_manager;

//import java.sql.*;
//import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
//import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import javax.swing.JOptionPane;
/**
 *
 * @author student
 */

public class Profile extends javax.swing.JFrame {

   
    /**
     * Creates new form Profile
     */
    private static final String DB_URL = "jdbc:mysql://sundar-d67dcb9-sundar-ebb3.j.aivencloud.com:23692/FinanceProject";
    private static final String DB_USER = "avnadmin";
    private static final String DB_PASSWORD = "AVNS_OxF1ifWF1d41VGmZ8yM";
    public String Username1;
    
    public Profile(String Uname) {
        Username1=Uname;
        setSize(1500, 900);
        initComponents();
         JUsername.setText(Username1);
         this.setLocationRelativeTo(null);
//center form middle of screen
               
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        JUsername = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label9 = new java.awt.Label();
        label5 = new java.awt.Label();
        label10 = new java.awt.Label();
        label6 = new java.awt.Label();
        JAge = new java.awt.Label();
        JEmail = new java.awt.Label();
        JName = new java.awt.Label();
        JOccupation = new java.awt.Label();
        JPhn = new java.awt.Label();
        JBudget = new java.awt.Label();
        JAddress = new java.awt.Label();
        JBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROFILE");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 910, 60));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1500, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personal_finance_manager/profile.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 280, 320));

        JUsername.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JUsername.setText("USERNAME");
        jPanel4.add(JUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 190, 30));

        label2.setBackground(new java.awt.Color(44, 62, 80));
        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setPreferredSize(new java.awt.Dimension(152, 26));
        label2.setText("NAME");
        jPanel4.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 290, 35));

        label3.setBackground(new java.awt.Color(44, 62, 80));
        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setPreferredSize(new java.awt.Dimension(152, 26));
        label3.setText("EMAIL");
        jPanel4.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 290, 35));

        label4.setBackground(new java.awt.Color(44, 62, 80));
        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setPreferredSize(new java.awt.Dimension(152, 26));
        label4.setText("PHN NUM");
        jPanel4.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 290, 35));

        label9.setBackground(new java.awt.Color(44, 62, 80));
        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setPreferredSize(new java.awt.Dimension(152, 26));
        label9.setText("AGE");
        jPanel4.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 290, 35));

        label5.setBackground(new java.awt.Color(44, 62, 80));
        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setPreferredSize(new java.awt.Dimension(152, 26));
        label5.setText("OCCUPATION");
        jPanel4.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 290, 35));

        label10.setBackground(new java.awt.Color(44, 62, 80));
        label10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setPreferredSize(new java.awt.Dimension(152, 26));
        label10.setText("BUDGET");
        jPanel4.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 290, 35));

        label6.setBackground(new java.awt.Color(44, 62, 80));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setPreferredSize(new java.awt.Dimension(152, 26));
        label6.setText("ADDRESS");
        jPanel4.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 290, 35));

        JAge.setBackground(new java.awt.Color(0, 204, 204));
        JAge.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JAge.setForeground(new java.awt.Color(255, 255, 255));
        JAge.setPreferredSize(new java.awt.Dimension(152, 26));
        JAge.setText("NAME");
        jPanel4.add(JAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 320, 35));

        JEmail.setBackground(new java.awt.Color(0, 204, 204));
        JEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JEmail.setForeground(new java.awt.Color(255, 255, 255));
        JEmail.setPreferredSize(new java.awt.Dimension(152, 26));
        JEmail.setText("NAME");
        jPanel4.add(JEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 320, 35));

        JName.setBackground(new java.awt.Color(0, 204, 204));
        JName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JName.setForeground(new java.awt.Color(255, 255, 255));
        JName.setPreferredSize(new java.awt.Dimension(152, 26));
        JName.setText("NAME");
        jPanel4.add(JName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 320, 35));

        JOccupation.setBackground(new java.awt.Color(0, 204, 204));
        JOccupation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JOccupation.setForeground(new java.awt.Color(255, 255, 255));
        JOccupation.setPreferredSize(new java.awt.Dimension(152, 26));
        JOccupation.setText("NAME");
        jPanel4.add(JOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 320, 35));

        JPhn.setBackground(new java.awt.Color(0, 204, 204));
        JPhn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JPhn.setForeground(new java.awt.Color(255, 255, 255));
        JPhn.setPreferredSize(new java.awt.Dimension(152, 26));
        JPhn.setText("NAME");
        jPanel4.add(JPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 320, 35));

        JBudget.setBackground(new java.awt.Color(0, 204, 204));
        JBudget.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBudget.setForeground(new java.awt.Color(255, 255, 255));
        JBudget.setPreferredSize(new java.awt.Dimension(152, 26));
        JBudget.setText("NAME");
        jPanel4.add(JBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 320, 35));

        JAddress.setBackground(new java.awt.Color(0, 204, 204));
        JAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JAddress.setForeground(new java.awt.Color(255, 255, 255));
        JAddress.setPreferredSize(new java.awt.Dimension(152, 26));
        JAddress.setText("NAME");
        jPanel4.add(JAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 320, 35));

        JBack.setBackground(new java.awt.Color(0, 204, 204));
        JBack.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personal_finance_manager/back.png"))); // NOI18N
        JBack.setText("BACK");
        JBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackActionPerformed(evt);
            }
        });
        jPanel4.add(JBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 130, 40));

        jLabel4.setBackground(new java.awt.Color(44, 62, 80));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Update Profile :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 180, 30));

        JUpdate.setBackground(new java.awt.Color(0, 204, 204));
        JUpdate.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personal_finance_manager/edit.png"))); // NOI18N
        JUpdate.setText("UPDATE");
        JUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(JUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 160, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackActionPerformed
        // TODO add your handling code here:
       //add a handle to go to homepage
       //new Homepage("Username1").setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBackActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
          try{
             Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement statement = connection.createStatement();
            String query = "select * from UserDetails where username='"+Username1+"'";
            ResultSet res=statement.executeQuery(query);
            while(res.next()){
                JName.setText(res.getString("name"));
                JEmail.setText(res.getString("emailId"));
                 JAge.setText(res.getString("age"));
                JOccupation.setText(res.getString("occupation"));
                JBudget.setText(res.getString("budget"));
                JAddress.setText(res.getString("city"));
                JPhn.setText(res.getString("phoneNo"));
               res.close();
            statement.close();
           // updateStatement.close();
            connection.close();
            }
        }
        catch(SQLException e){
            //JOptionPane.showMessageDialog(null,e);
           e.printStackTrace();
        }

    }//GEN-LAST:event_formComponentShown

    private void JUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateActionPerformed
        // TODO add your handling code here:
         new Update(Username1).setVisible(true);
        this.dispose();  //to close profile page
    }//GEN-LAST:event_JUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        String user="manu";
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                new Profile(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label JAddress;
    private java.awt.Label JAge;
    private javax.swing.JButton JBack;
    private java.awt.Label JBudget;
    private java.awt.Label JEmail;
    private java.awt.Label JName;
    private java.awt.Label JOccupation;
    private java.awt.Label JPhn;
    private javax.swing.JButton JUpdate;
    private javax.swing.JLabel JUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
