/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personal_finance_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    private static final String DB_URL = "jdbc:mysql://sundar-d67dcb9-sundar-ebb3.j.aivencloud.com:23692/FinanceProject";
    private static final String DB_USER = "avnadmin";
    private static final String DB_PASSWORD = "AVNS_OxF1ifWF1d41VGmZ8yM";
    public String Username1;
    public Update(String Uname) {
        Username1=Uname;
        new Profile(Username1).setVisible(false);  
        
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lable1 = new java.awt.Label();
        label3 = new java.awt.Label();
        lable3 = new java.awt.Label();
        lable4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        JName = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        JAge = new javax.swing.JTextField();
        JOccupation = new javax.swing.JTextField();
        JBudget = new javax.swing.JTextField();
        lable = new java.awt.Label();
        label9 = new java.awt.Label();
        JPassword = new javax.swing.JTextField();
        JConfirm = new javax.swing.JPasswordField();
        JPhn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label10 = new java.awt.Label();
        JAddress = new javax.swing.JTextField();
        JSave = new javax.swing.JButton();
        JBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 66));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 1400, 10));

        lable1.setBackground(new java.awt.Color(44, 62, 80));
        lable1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 255, 255));
        lable1.setPreferredSize(new java.awt.Dimension(152, 26));
        lable1.setText("Name");
        getContentPane().add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 270, 30));

        label3.setBackground(new java.awt.Color(44, 62, 80));
        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setPreferredSize(new java.awt.Dimension(152, 26));
        label3.setText("Email");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 270, 30));

        lable3.setBackground(new java.awt.Color(44, 62, 80));
        lable3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lable3.setForeground(new java.awt.Color(255, 255, 255));
        lable3.setPreferredSize(new java.awt.Dimension(152, 26));
        lable3.setText("Age");
        getContentPane().add(lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 270, 30));

        lable4.setBackground(new java.awt.Color(44, 62, 80));
        lable4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lable4.setForeground(new java.awt.Color(255, 255, 255));
        lable4.setPreferredSize(new java.awt.Dimension(152, 26));
        lable4.setText("Occupation");
        getContentPane().add(lable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 270, 30));

        label6.setBackground(new java.awt.Color(44, 62, 80));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setPreferredSize(new java.awt.Dimension(152, 26));
        label6.setText("Budget");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 270, 30));

        label7.setBackground(new java.awt.Color(44, 62, 80));
        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setPreferredSize(new java.awt.Dimension(152, 26));
        label7.setText("Confirm Password");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 270, 30));

        JName.setBackground(new java.awt.Color(0, 204, 204));
        JName.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JName.setForeground(new java.awt.Color(255, 255, 255));
        JName.setPreferredSize(new java.awt.Dimension(152, 26));
        JName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNameActionPerformed(evt);
            }
        });
        getContentPane().add(JName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 340, 30));

        JEmail.setBackground(new java.awt.Color(0, 204, 204));
        JEmail.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JEmail.setForeground(new java.awt.Color(255, 255, 255));
        JEmail.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 340, 30));

        JAge.setBackground(new java.awt.Color(0, 204, 204));
        JAge.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JAge.setForeground(new java.awt.Color(255, 255, 255));
        JAge.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 340, 30));

        JOccupation.setBackground(new java.awt.Color(0, 204, 204));
        JOccupation.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JOccupation.setForeground(new java.awt.Color(255, 255, 255));
        JOccupation.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 340, 30));

        JBudget.setBackground(new java.awt.Color(0, 204, 204));
        JBudget.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JBudget.setForeground(new java.awt.Color(255, 255, 255));
        JBudget.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 340, 30));

        lable.setBackground(new java.awt.Color(44, 62, 80));
        lable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lable.setForeground(new java.awt.Color(255, 255, 255));
        lable.setPreferredSize(new java.awt.Dimension(152, 26));
        lable.setText("PhnNo");
        getContentPane().add(lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 270, 30));

        label9.setBackground(new java.awt.Color(44, 62, 80));
        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setPreferredSize(new java.awt.Dimension(152, 26));
        label9.setText("New Pasword");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 270, 30));

        JPassword.setBackground(new java.awt.Color(0, 204, 204));
        JPassword.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        JPassword.setForeground(new java.awt.Color(255, 255, 255));
        JPassword.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 340, 30));

        JConfirm.setBackground(new java.awt.Color(0, 204, 204));
        JConfirm.setPreferredSize(new java.awt.Dimension(152, 26));
        getContentPane().add(JConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 340, 30));

        JPhn.setBackground(new java.awt.Color(0, 204, 204));
        JPhn.setColumns(3);
        JPhn.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        JPhn.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JPhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 340, 30));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Enter if needed* :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 160, 40));

        label10.setBackground(new java.awt.Color(44, 62, 80));
        label10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setPreferredSize(new java.awt.Dimension(152, 26));
        label10.setText("Address");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 270, 30));

        JAddress.setBackground(new java.awt.Color(0, 204, 204));
        JAddress.setColumns(3);
        JAddress.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        JAddress.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 340, 30));

        JSave.setBackground(new java.awt.Color(51, 208, 0));
        JSave.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JSave.setForeground(new java.awt.Color(255, 255, 255));
        JSave.setText("Save");
        JSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JSave.setMinimumSize(new java.awt.Dimension(65, 30));
        JSave.setPreferredSize(new java.awt.Dimension(65, 32));
        JSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSaveActionPerformed(evt);
            }
        });
        getContentPane().add(JSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 130, 40));

        JBack.setBackground(new java.awt.Color(0, 204, 204));
        JBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBack.setForeground(new java.awt.Color(255, 255, 255));
        JBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personal_finance_manager/back.png"))); // NOI18N
        JBack.setText("Back");
        JBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JBack.setMinimumSize(new java.awt.Dimension(65, 30));
        JBack.setPreferredSize(new java.awt.Dimension(65, 32));
        JBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackActionPerformed(evt);
            }
        });
        getContentPane().add(JBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNameActionPerformed
/**/
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement statement = connection.createStatement();
            String query = "select * from UserDetails where username='" + Username1 + "'";
            ResultSet res = statement.executeQuery(query);
            while (res.next()) {
                JName.setText(res.getString("name"));
                JEmail.setText(res.getString("emailId"));
                JAge.setText(res.getString("age"));
                JOccupation.setText(res.getString("occupation"));
                JBudget.setText(res.getString("budget"));
                JAddress.setText(res.getString("city"));
                JPhn.setText(res.getString("phoneNo"));
                res.close();
                statement.close();
                // updateStatement.close();
                connection.close();
            }
        } catch (SQLException e) {
            // JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_formComponentShown

    private void JSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSaveActionPerformed
        // TODO add your handling code here:
           int flag=0;
        String pass = JPassword.getText();
        if (!JPassword.getText().equals("")) //for Confirm Password field
        {
            if (!JConfirm.getText().equals(JPassword.getText())) {
                JOptionPane.showMessageDialog(null, "password not matched");
                flag=1;
                setVisible(true);
            }
            try {
                Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
                Statement statement = connection.createStatement();

                String query = "update UserDetails set password='" + pass + "'where username='" + Username1 + "'";
                // PreparedStatement update = connection.prepareStatement(query);
                int row = statement.executeUpdate(query);
                statement.close();
                connection.close();

                //update.executeQuery();
            } catch (SQLException e) {
                // JOptionPane.showMessageDialog(null,e);
                e.printStackTrace();
            }
        }

        String name = JName.getText();
        String email = JEmail.getText();
        String age = JAge.getText();
        String occupation = JOccupation.getText();
        String Budget = JBudget.getText();
        String add = JAddress.getText();
        String phn = JPhn.getText();
         String query = "update UserDetails set name=?,emailId=?,phoneNo=?,age=?,occupation=?,city=?,budget=? where username='"+Username1+"'";
        try {
            Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement statement = connection.createStatement();
           
            //String query = "update UserDetails set password='"+pass+"'where username='"+Username1+"'";
            PreparedStatement update = connection.prepareStatement(query);
            update.setString(1, name);
            update.setString(2, email);
            update.setString(3, phn);
            update.setString(4, age);
            update.setString(5, occupation);
            update.setString(6, add);
            update.setString(7, Budget);
           // update.setString(8, Username1);
            update.executeUpdate();
            statement.close();
            connection.close();
            //update.executeQuery();
        } catch (SQLException e) {
            // JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
         if(flag!=1){
        JOptionPane.showMessageDialog(null, "Update Successful");
        new Profile(Username1).setVisible(true);     
         }
        
      
        
                                   
        
    }//GEN-LAST:event_JSaveActionPerformed

    private void JBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackActionPerformed
        // TODO add your handling code here:
         new Profile(Username1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JAddress;
    private javax.swing.JTextField JAge;
    private javax.swing.JButton JBack;
    private javax.swing.JTextField JBudget;
    private javax.swing.JPasswordField JConfirm;
    private javax.swing.JTextField JEmail;
    private javax.swing.JTextField JName;
    private javax.swing.JTextField JOccupation;
    private javax.swing.JTextField JPassword;
    private javax.swing.JTextField JPhn;
    private javax.swing.JButton JSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label10;
    private java.awt.Label label3;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label9;
    private java.awt.Label lable;
    private java.awt.Label lable1;
    private java.awt.Label lable3;
    private java.awt.Label lable4;
    // End of variables declaration//GEN-END:variables
}
